app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/camunda
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass

camunda.bpm:
  database:
    schema-update: true
  history-level: audit

logging:
  level:
    com.example.workflow: debug